package com.envelo.businesstrip.model.enums;

public enum ExpenseReportStatus {
    EMPLOYEE_DRAFT,
    PENDING_SUPERVISOR_REVIEW,
    PENDING_EMPLOYEE_CORRECTION,
    PENDING_SUPERVISOR_ACCOUNTANT,
    PENDING_SUPERVISOR_CORRECTION,
    FINISHED
}
